-- CREATE JXWU_USER_1
CREATE ROLE JXWU_ROLE_1;
CREATE USER JXWU_USER_1 WITH PASSWORD 'hillstone';
GRANT ROLE JXWU_ROLE_1 TO USER JXWU_USER_1;
-- CREATE JXWU_TABLE_1
CREATE TABLE JXWU_USER_1.JXWU_TABLE_1 (JXWU_COLUMN_1 VARCHAR(64) NOT NULL);
COMMENT ON COLUMN JXWU_USER_1.JXWU_TABLE_1.JXWU_COLUMN_1 IS 'jxwu_user_1.JXWU_TABLE_1.jxwu_column_1';
CREATE TABLE JXWU_USER_1.JXWU_TABLE_2 (JXWU_COLUMN_1 VARCHAR(64) NOT NULL);
COMMENT ON COLUMN JXWU_USER_1.JXWU_TABLE_2.JXWU_COLUMN_1 IS 'jxwu_user_1.jxwu_table_2.jxwu_column_1';
-- CREATE JXWU_USER_2
CREATE USER JXWU_USER_2 WITH PASSWORD 'hillstone';
GRANT ROLE JXWU_ROLE_1 TO USER JXWU_USER_2;
GRANT ROLE SYSDBA TO USER JXWU_USER_2;
-- GET_SCHEMAS
SELECT TABLE_SCHEM AS SCHEMA_NAME
FROM INFO_SCHEM.V_SYS_SCHEMAS
WHERE TABLE_SCHEM IN ('JXWU_USER_1');
-- GET_TABLES
SELECT T.SCHEMANAME AS SCHEMA_NAME,
  T.TABLENAME AS TABLE_NAME,
  TS.REMARKS AS TABLE_COMMENTS
FROM INFO_SCHEM.V_SYS_TABLE T
  LEFT JOIN INFO_SCHEM.V_SYS_TABLES TS ON T.SCHEMANAME = TS.TABLE_SCHEM
  AND T.TABLENAME = TS.TABLE_NAME
WHERE T.SCHEMANAME IN ('JXWU_USER_1')
  AND T.TABLENAME IN ('JXWU_TABLE_1');
-- GET_COLUMNS
SELECT TABLE_SCHEM AS SCHEMA_NAME,
  TABLE_NAME AS TABLE_NAME,
  COLUMN_NAME AS COLUMN_NAME,
  TYPE_NAME AS DATA_TYPE,
  REMARKS AS COLUMN_COMMENTS
FROM INFO_SCHEM.V_SYS_COLUMNS
WHERE TABLE_SCHEM IN ('JXWU_USER_1')
  AND TABLE_NAME IN ('JXWU_TABLE_1');
-- GET_USERS_FOR_DBA
SELECT U.USERNAME,
  P.GRANTED_ROLE
FROM INFO_SCHEM.DBA_USERS U
  LEFT JOIN INFO_SCHEM.DBA_ROLE_PRIVS P ON U.USERNAME = P.GRANTEE;
-- GET_USERS_FOR_ALL
SELECT U.USERNAME,
  P.GRANTED_ROLE
FROM INFO_SCHEM.ALL_USERS U
  LEFT JOIN INFO_SCHEM.USER_ROLE_PRIVS P ON U.USERNAME = P.USERNAME;
-- GET_ROLES_FOR_DBA
SELECT R.ROLE,
  P.GRANTED_ROLE
FROM INFO_SCHEM.DBA_ROLES R
  LEFT JOIN INFO_SCHEM.DBA_ROLE_PRIVS P ON R.ROLE = P.GRANTEE;
-- GET_ROLES_FOR_ALL
SELECT GRANTED_ROLE AS ROLE,
  NULL AS GRANTED_ROLE
FROM INFO_SCHEM.USER_ROLE_PRIVS;
-- GET_USERS_SYS_PRIVS_FOR_DBA
SELECT U.USERNAME,
  S.PRIVILEGE
FROM INFO_SCHEM.DBA_USERS U
  LEFT JOIN INFO_SCHEM.DBA_ROLE_PRIVS P ON U.USERNAME = P.GRANTEE
  LEFT JOIN INFO_SCHEM.DBA_SYS_PRIVS S ON (
    P.GRANTED_ROLE = S.GRANTEE
    OR U.USERNAME = S.GRANTEE
  )
WHERE U.USERNAME IN ('JXWU_USER_1');
-- GET_USERS_SYS_PRIVS_FOR_ALL
SELECT U.USERNAME,
  S.PRIVILEGE
FROM INFO_SCHEM.ALL_USERS U
  LEFT JOIN INFO_SCHEM.USER_ROLE_PRIVS P ON U.USERNAME = P.USERNAME
  LEFT JOIN INFO_SCHEM.USER_SYS_PRIVS S ON (
    P.GRANTED_ROLE = S.USERNAME
    OR U.USERNAME = S.USERNAME
  )
WHERE U.USERNAME IN ('JXWU_USER_1');
-- GET_USERS_TAB_PRIVS_FOR_DBA
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS USERNAME
FROM INFO_SCHEM.DBA_TABLES T
  INNER JOIN INFO_SCHEM.DBA_TAB_PRIVS P ON T.OWNER = P.OWNER
  AND T.TABLE_NAME = P.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_USER_1');
-- GET_USERS_TAB_PRIVS_FOR_ALL
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS USERNAME
FROM INFO_SCHEM.ALL_TABLES T
  INNER JOIN INFO_SCHEM.ALL_TAB_PRIVS P ON T.OWNER = P.TABLE_SCHEMA
  AND T.TABLE_NAME = P.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_USER_1');
-- GET_USERS_COL_PRIVS_FOR_DBA
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.COLUMN_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS USERNAME
FROM INFO_SCHEM.DBA_TABLES T
  INNER JOIN INFO_SCHEM.DBA_COL_PRIVS P ON T.OWNER = P.OWNER
  AND T.TABLE_NAME = P.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_USER_1');
-- GET_USERS_COL_PRIVS_FOR_ALL
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.COLUMN_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS USERNAME
FROM INFO_SCHEM.ALL_TABLES T
  INNER JOIN INFO_SCHEM.ALL_COL_PRIVS P ON T.OWNER = P.TABLE_SCHEMA
  AND T.TABLE_NAME = P.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_USER_1');
-- GET_ROLES_SYS_PRIVS_FOR_DBA
SELECT R.ROLE,
  P.PRIVILEGE
FROM INFO_SCHEM.DBA_ROLES R
  LEFT JOIN INFO_SCHEM.DBA_SYS_PRIVS P ON R.ROLE = P.GRANTEE
WHERE R.ROLE IN ('JXWU_ROLE_1');
-- GET_ROLES_SYS_PRIVS_FOR_ALL
SELECT GRANTED_ROLE AS ROLE,
  S.PRIVILEGE
FROM INFO_SCHEM.USER_ROLE_PRIVS R
  LEFT JOIN INFO_SCHEM.USER_SYS_PRIVS S ON R.GRANTED_ROLE = S.USERNAME
WHERE GRANTED_ROLE IN ('JXWU_ROLE_1');
-- GET_ROLES_TAB_PRIVS_FOR_DBA
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS ROLE
FROM INFO_SCHEM.DBA_ROLES R
  INNER JOIN INFO_SCHEM.DBA_TAB_PRIVS P ON R.ROLE = P.GRANTEE
  INNER JOIN INFO_SCHEM.DBA_TABLES T ON P.OWNER = T.OWNER
  AND P.TABLE_NAME = T.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_ROLE_1');
-- GET_ROLES_TAB_PRIVS_FOR_ALL
SELECT R.GRANTED_ROLE AS ROLE,
  T.TABLE_SCHEMA AS SCHEMA_NAME,
  TABLE_NAME,
  PRIVILEGE
FROM INFO_SCHEM.USER_ROLE_PRIVS R
  LEFT JOIN INFO_SCHEM.ALL_TAB_PRIVS T ON R.GRANTED_ROLE = T.GRANTEE
WHERE R.GRANTED_ROLE IN ('JXWU_ROLE_1');
-- GET_ROLES_COL_PRIVS_FOR_DBA
SELECT T.OWNER AS SCHEMA_NAME,
  T.TABLE_NAME,
  P.COLUMN_NAME,
  P.PRIVILEGE,
  P.GRANTEE AS ROLE
FROM INFO_SCHEM.DBA_ROLES R
  INNER JOIN INFO_SCHEM.DBA_COL_PRIVS P ON R.ROLE = P.GRANTEE
  INNER JOIN INFO_SCHEM.DBA_TABLES T ON P.OWNER = T.OWNER
  AND P.TABLE_NAME = T.TABLE_NAME
WHERE P.GRANTEE IN ('JXWU_ROLE_1');
-- GET_ROLES_COL_PRIVS_FOR_ALL
SELECT R.GRANTED_ROLE AS ROLE,
  COLUMN_NAME,
  PRIVILEGE,
  TABLE_SCHEMA AS SCHEMA_NAME,
  TABLE_NAME
FROM INFO_SCHEM.USER_ROLE_PRIVS R
  LEFT JOIN INFO_SCHEM.ALL_COL_PRIVS T ON R.GRANTED_ROLE = T.GRANTEE
WHERE R.GRANTED_ROLE IN ('JXWU_ROLE_1');
-- GET_SAMPLING_DATA
SELECT %s
FROM %s. %s
LIMIT %s;