apiVersion: v1
kind: ConfigMap
metadata:
  name: application-service
  namespace: cloud-vod
data:
  application-service.yml: |
    cloud:
      platform:
        service:
          cloud-vod:
            vod-capture:
              host: vod-capture.cloud-vod.svc.cluster.local
              port: 80
              url: http://${cloud.platform.service.cloud-vod.vod-capture.host}:${cloud.platform.service.cloud-vod.vod-capture.port}
    spring:
      profiles:
        active: china,test
