apiVersion: v1
kind: ConfigMap
metadata:
  name: application-env
  namespace: cloud-vod
data:
  application-env.yml: |
    cloud:
      foundation:
        vod-mysql-cluster:
          url: 10.182.220.101:3306
          username: root
          password: hillstone
        vod-clickhouse-cluster:
          url: 10.182.220.101:8223
          username: hillstone
          password: hillstone
        redis-cluster:
          url: 10.182.139.129:8001,10.182.139.129:8002,10.182.139.130:8001,10.182.139.130:8002,10.182.139.131:8001,10.182.139.131:8002
          password: hillstoneHSM4Ever
        elasticsearch:
          host: 10.182.139.55
          port: 9200
          username: elastic
          password: hillstone
        hillstone-oauth-server-url: https://user.hillstonenet.com.cn
        hillstone-cloud-server-url: https://cloud.hillstonenet.com.cn
        hillstone-vod-server-url: https://vod.hillstonenet.com.cn
        vod-detection:
          ip: 10.182.220.101
          port: 19011
    spring:
      profiles:
        active: china,beta
